language: python
python:
  - "3.8"

# Define environment variables
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

# command to install dependencies
install:
  - pip install pipenv
  - pipenv sync -d
# command to run tests
script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov
